# Configuration for the Insurance Taxonomy Classifier project

# Preprocessing parameters
preprocessing:
  remove_stopwords: true
  min_word_length: 2
  lemmatize: true

# Embedding parameters
embeddings:
  model_name: "all-MiniLM-L6-v2"  # Model from sentence-transformers
  max_seq_length: 128
  cache_dir: "../data/embeddings"

# Clustering parameters
clustering:
  algorithm: "kmeans"  # Other options: "dbscan", "hdbscan"
  n_clusters: 50       # For k-means
  min_cluster_size: 5  # For DBSCAN/HDBSCAN

# Classification parameters
classification:
  similarity_threshold: 0.5
  top_k_labels: 3
