# Configuration for the Insurance Taxonomy Classifier project

# Path configuration
paths:
  companies_data: "ml_insurance_challenge.csv"
  taxonomy_data: "insurance_taxonomy.csv"
  output_dir: "results"
  model_dir: "models"

# Preprocessing parameters
preprocessing:
  remove_stopwords: true
  min_word_length: 2
  lemmatize: true
  combine_fields: true  # Whether to combine company description and tags

# Embedding parameters
embeddings:
  model_name: "all-MiniLM-L6-v2"  # Model from sentence-transformers
  max_seq_length: 128
  cache_dir: "data/embeddings"
  batch_size: 32

# Clustering parameters
clustering:
  algorithm: "kmeans"  # Options: "kmeans", "dbscan"
  n_clusters: 50       # For k-means
  min_cluster_size: 5  # For DBSCAN
  eps: 0.5             # For DBSCAN
  visualize: true
  analysis_top_n_words: 15

# Classification parameters
classification:
  similarity_threshold: 0.45  # Minimum similarity to assign a label
  top_k_labels: 3            # Maximum number of labels to assign per company
  use_clustering: false      # Whether to use clustering to inform classification

# Evaluation parameters
evaluation:
  test_size: 0.2        # Fraction of data to use for testing
  random_seed: 42       # Random seed for reproducibility
  metrics: ["precision", "recall", "f1"]  # Metrics to evaluate