# Configuration for the Insurance Taxonomy Classifier project

# Path configuration
paths:
  companies_data: "ml_insurance_challenge.csv"
  taxonomy_data: "insurance_taxonomy.csv"
  output_dir: "results"
  model_dir: "models"

# Preprocessing parameters
preprocessing:
  remove_stopwords: true
  min_word_length: 2
  lemmatize: true

# Embedding parameters
embeddings:
  model_name: "all-MiniLM-L6-v2"
  max_seq_length: 128
  cache_dir: "data/embeddings"
  batch_size: 32

# Classification parameters
classification:
  similarity_threshold: 0.35
  top_k_labels: 3
  min_similarity_score: 0.25

# Evaluation parameters
evaluation:
  test_size: 0.2
  random_seed: 42
  metrics: ["precision", "recall", "f1"]

# Optional: Configuration for sector-based classification
sector_classification:
  min_confidence: 0.3
  top_k_labels: 3